# > VARIÁVEIS

# 1. Variáveis

Idade = 26 # Criando uma varíavel 

print (Idade)

Nome = 'Ollyzinho'

print (Nome)
"""
Tipos de variáveis
1. Int: Números inteiros, ou seja, números sem parte decimal: 0,5, -1, 1000
2. Float: Números reais, ou seja, número com parte decimal: 1.0, -2.7, 3.14
3. str: cadeia de caracteres, ou seja, dados textutais (string)
4. bool: Valores lógicos (booleanos): True ou False
"""
Idade = 26
altura = 1.77
Nome = Ollyzinho
Estudando = True

print ( type(Idade))
print ( type (altura))
print ( type (Nome))
print ( type (Estudando))
